spring:
  application:
    name: panoramix.com
  datasource:
    url: jdbc:h2:file:/app/data/mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # ou 'create-drop' en dev, mais pas en prod
    show-sql: true
    database-plateform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: panoramix.irreductible@gmail.com
    password: ${{GMAIL_PASS}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
server:
  port: 3001
  servlet:
    context-path: /api