spring:
  application:
    name: panoramix.com
  datasource:
    url: jdbc:postgresql://tramway.proxy.rlwy.net:47385/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
server:
  port: 3001
  servlet:
    context-path: /api